# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HydrodynamicSolver
                                 A QGIS plugin
 This puging counts river flow.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-06
        copyright            : (C) 2026 by @OllyVas @girl_under_the_rain @drakon_v_tapkax
        email                : voa77777@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = '@OllyVas @girl_under_the_rain @drakon_v_tapkax'
__date__ = '2026-03-06'
__copyright__ = '(C) 2026 by @OllyVas @girl_under_the_rain @drakon_v_tapkax'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HydrodynamicSolver class from file HydrodynamicSolver.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hydrodynamic_solver import HydrodynamicSolverPlugin
    return HydrodynamicSolverPlugin(iface)
