# -*- coding: utf-8 -*-

"""
/***************************************************************************
 HydrodynamicSolver
                                 A QGIS plugin
 This puging counts river flow.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-06
        copyright            : (C) 2026 by @OllyVas @girl_under_the_rain @drakon_v_tapkax
        email                : voa77777@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = '@OllyVas @girl_under_the_rain @drakon_v_tapkax'
__date__ = '2026-03-06'
__copyright__ = '(C) 2026 by @OllyVas @girl_under_the_rain @drakon_v_tapkax'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect
from PyQt5.QtWidgets import QAction
from PyQt5.QtGui import QIcon

from .solver_dialog import SolverDialog
from .solverCore import SolverCore

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from qgis.core import QgsRasterLayer, QgsProject, QgsCoordinateReferenceSystem

# from .hydrodynamic_solver_provider import HydrodynamicSolverProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class HydrodynamicSolverPlugin(object):

    def __init__(self, iface):
        self.provider = None
        self.iface = iface
        self.dlg = None
        self.dockOpened = False 

    # def initProcessing(self):
    #     """Init Processing provider for QGIS >= 3.8."""
    #     self.provider = HydrodynamicSolverProvider()
    #     QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        icon = os.path.join(os.path.join(cmd_folder, 'logo.png'))
        self.action = QAction(QIcon(icon), 'Load Basemap', self.iface.mainWindow())
        self.iface.addToolBarIcon(self.action)
        self.action.triggered.connect(self.run)

        #self.initProcessing()

    def run(self):

        if not self.dockOpened:
            # if self.profiletool is None:
            self.solver = SolverCore(self.iface, self)
            self.iface.addDockWidget(
                self.solver.dockwidget.location, self.solver.dockwidget
            )
            self.solver.dockwidget.closed.connect(self.cleaning)
            self.dockOpened = True

        

        # if self.dlg is None:
        #     self.dlg = SolverDialog(self.iface, self.iface.mainWindow())
        # self.dlg.show()
        # self.dlg.raise_()
        # self.dlg.activateWindow()

        # basemap_url = 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
        # zmin = 0
        # zmax = 19
        # crs = 'EPSG:3857'
        
        # # Replace '=' and '&' in the URL to ensure it is properly encoded
        # encoded_url = basemap_url.replace('=', '%3D').replace('&', '%26')
        # uri = f'type=xyz&url={encoded_url}&zmax={zmax}&zmin={zmin}$crs={crs}'
        
        # # Create a QgsRasterLayer with the URI
        # rlayer = QgsRasterLayer(uri, 'OpenStreetMap', 'wms')
        # if rlayer.isValid():
        #     QgsProject.instance().addMapLayer(rlayer)
        #     self.iface.messageBar().pushSuccess('Success', 'Basemap Layer Loaded')
        # else:
        #     self.iface.messageBar().pushCritical('Error', 'Invalid Basemap Layer')

    def cleaning(self):
        return


    def unload(self):
        # QgsApplication.processingRegistry().removeProvider(self.provider)
        self.iface.removeToolBarIcon(self.action)
        del self.action


